In [1]:
import numpy as np
import engine

In [3]:
n = np.arange(50).reshape(5,10)
print(n)
X = [0, 3, 4]

n[0,X].sum()


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


7

In [13]:
for _ in range(4):
    print("x")

x
x
x
x


In [19]:
x = np.array([2,34,5,12,3,2,4,78,3])
where = np.where(x == x.min())[0][0]
x = list(x)
x[(len(x)-1):]

[3]